name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  jenkins-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar Jenkins remotamente
        run: |
          curl -X POST "$JENKINS_URL/job/web-content/build?token=gts5302b"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
